#!/usr/bin/sh
# $exitDir "/home/david/.i3"
$stopDir "/home/david/.i3/scripts/tw-stop.sh"
lock() {
    bash lock.sh -l dimblur
}

echo "test" >> testfile
case "$1" in
    lock)
        bash lock.sh -l dimblur
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        bash $stopDir

        systemctl suspend | bash lock.sh -l dimblur
        #       bash lock.sh -l dimblur && echo mem > /sys/power/state
	      ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
