#!/bin/bash

#current task
task=""
id=""
due=""
#only gets the first description
task=$(task _get $(task +ACTIVE _id).description)
if [[ ! -z $task ]]; then
#	due=$(task _get $(task +ACTIVE _id).due)
	echo "Active: $task"
fi
